global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'app_metrics'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'solana'
    static_configs:
      - targets: ['localhost:8899']  # Default Solana RPC port
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'solana-validator'
    static_configs:
      - targets: ['localhost:8899']  # Default Solana validator metrics port
    metrics_path: '/metrics'
    scheme: 'http'
